name = "Mods For The Pack"
author = "Vivian"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d99f121488182a4aa6bd67e5a6a2c40644498651fcd0012088df6b50ccce9659"

[versions]
minecraft = "1.19.2"
quilt = "0.26.0"
