name = "Mods For The Pack"
author = "Vivian"
version = "1.1.26"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bfd0f32189a83fcaff73416f21f44bbc9fe43334c2fb3aab348a241bd6c52aa1"

[versions]
minecraft = "1.19.2"
quilt = "0.26.0"
