name = "Mods For The Pack"
author = "Vivian"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b3ae28fe68866d7252487e8401d2733ed67ab24d63e843888bbf2acf11f13a92"

[versions]
minecraft = "1.19.2"
quilt = "0.27.0-beta.1"
