name = "Mods For The Pack"
author = "Vivian"
version = "1.1.14"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0a272aeb423dcb7e68197f210d6577ed2fa8519be270ffad428c575e406ea946"

[versions]
minecraft = "1.19.2"
quilt = "0.26.0"
