name = "Mods For The Pack"
author = "Vivian"
version = "1.0.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2cd317e4ecc429168e434dd6e6b6c95fac1e89c6867d25e86b668eab663dff68"

[versions]
minecraft = "1.19.2"
quilt = "0.26.0"
