name = "Mods For The Pack"
author = "Vivian"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "863c613b5f92a75eea7b829e2664061f2e213540524a1f13f24f9c4a821a1791"

[versions]
minecraft = "1.19.2"
quilt = "0.26.0"
