name = "Mods For The Pack"
author = "Vivian"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b1a28808fe78808dadd73814bc302d774f58d2928581fb785aebe6f8cda99f60"

[versions]
minecraft = "1.19.2"
quilt = "0.26.0"
