name = "Mods For The Pack"
author = "Vivian"
version = "1.6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1b489094f0834ea8a2c5b3f3e4e3f4bef3f402931aadc9856895003f546d8183"

[versions]
minecraft = "1.19.2"
quilt = "0.27.0"
