name = "Mods For The Pack"
author = "Vivian"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8ea9074155256532b7486a4bf92e161eae51da9a6ba797ca03bc46cb23616713"

[versions]
minecraft = "1.19.2"
quilt = "0.27.0-beta.1"
