name = "Mods For The Pack"
author = "Vivian"
version = "1.1.21"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "377db357d983dbcb451347ead76078f11f692a6a0a187e9e663c2c7ab984f16e"

[versions]
minecraft = "1.19.2"
quilt = "0.26.0"
