name = "Mods For The Pack"
author = "Vivian"
version = "1.5.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e6ac6eb32ccf1c580d18477f72f3c14c32110da6792b3346214fa4263cc3a566"

[versions]
minecraft = "1.19.2"
quilt = "0.26.0"
