name = "Mods For The Pack"
author = "Vivian"
version = "1.5.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "58b3a77650373fa581617ec72b8f383aefba94b1cfae0950cffcf17974ff4c88"

[versions]
minecraft = "1.19.2"
quilt = "0.26.0"
