name = "Mods For The Pack"
author = "Vivian"
version = "1.2.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c5e8d84cb1412a556955863e2fc737c55f34ae51b39eb0b43b080ec1a4f7b441"

[versions]
minecraft = "1.19.2"
quilt = "0.26.0"
