name = "Mods For The Pack"
author = "Vivian"
version = "1.3.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5500d2a5b1808c8519d7c4d7a204425eb89f4a92c9c21e8c533190780f9180cc"

[versions]
minecraft = "1.19.2"
quilt = "0.26.0"
