name = "Mods For The Pack"
author = "Vivian"
version = "1.6.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4d94232492e9c9841ed0bb2d11fe9e5d169aefbf10bac163515ed5303e086cd5"

[versions]
minecraft = "1.19.2"
quilt = "0.27.0"
