name = "Mods For The Pack"
author = "Vivian"
version = "1.5.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "102dac9246664ad0cfef13a981243befae6e14f231ea91ec79d642611af22533"

[versions]
minecraft = "1.19.2"
quilt = "0.26.0"
