name = "Mods For The Pack"
author = "Vivian"
version = "1.2.14"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ad793111fed7a061d7b31cc714cb3c14b45f61705506a02c8d6595fcbe9f90c4"

[versions]
minecraft = "1.19.2"
quilt = "0.26.0"
