name = "Mods For The Pack"
author = "Vivian"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9a3856800ca05ea4882cf4672f1017b9adb24cfe3adc27816b0f49744c84d55e"

[versions]
minecraft = "1.19.2"
quilt = "0.26.0"
