name = "Mods For The Pack"
author = "Vivian"
version = "1.4.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1a4dd4f1e99ebeda83602b2379ff69aaa10494efe5edacd76a43db45eed722be"

[versions]
minecraft = "1.19.2"
quilt = "0.26.0"
