name = "Mods For The Pack"
author = "Vivian"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "56c16731f9ad31b38527adfbce716b8bc0e258214d14c69da4d06df5d0313366"

[versions]
minecraft = "1.19.2"
quilt = "0.26.0"
