name = "Mods For The Pack"
author = "Vivian"
version = "1.2.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fe733c9f1a279078489842571891bf25b01cc7ac48b8e3d1d8f00d36d762c4c9"

[versions]
minecraft = "1.19.2"
quilt = "0.26.0"
