name = "Mods For The Pack"
author = "Vivian"
version = "1.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "34afd39df852399bad41a9ba7d93abf566a0bdd2c652ff4210c9a9d66274a163"

[versions]
minecraft = "1.19.2"
quilt = "0.26.0"
