name = "Mods For The Pack"
author = "Vivian"
version = "1.1.29"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6ac5312238a8f9d253386e33ef85b8620b05e1083ca0d7c251a3a24b476e2322"

[versions]
minecraft = "1.19.2"
quilt = "0.26.0"
