name = "Mods For The Pack"
author = "Vivian"
version = "1.0.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2e1f076d7f286afc845fc7c612fecf9e7e13a20b61666b2207ec72b54cbacb06"

[versions]
minecraft = "1.19.2"
quilt = "0.26.0"
