name = "Mods For The Pack"
author = "Vivian"
version = "1.1.14"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3efa1ec0d6181c3f903e23507fc98ff9100f745eb1d77a41dd3c6b66a3c1402a"

[versions]
minecraft = "1.19.2"
quilt = "0.26.0"
