name = "Mods For The Pack"
author = "Vivian"
version = "1.2.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "62231ad8153059b0098e9c1126d30c54afc6486537082cefa2bcc50236d05ae3"

[versions]
minecraft = "1.19.2"
quilt = "0.26.0"
