name = "Mods For The Pack"
author = "Vivian"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e27d5bf82c3a679f87e082d9d6d3d9606a1beea04400d57561fe13c2b58fb8ee"

[versions]
minecraft = "1.19.2"
quilt = "0.27.0-beta.1"
