name = "Mods For The Pack"
author = "Vivian"
version = "1.1.11"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "900771cb53edd7dbcb1e6385dc709f719c9415c85545e631f384d96848979262"

[versions]
minecraft = "1.19.2"
quilt = "0.26.0"
