name = "Mods For The Pack"
author = "Vivian"
version = "1.1.24"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "827d25c860f27ad3e529466bfd15385f98a74035618f4d806d7568a24a94c45a"

[versions]
minecraft = "1.19.2"
quilt = "0.26.0"
