name = "Mods For The Pack"
author = "Vivian"
version = "1.3.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "75d2dacc2bd58365e1bbbb8d1221993a1a90265c70f06dbaa49ff6705190b4d1"

[versions]
minecraft = "1.19.2"
quilt = "0.26.0"
