name = "Mods For The Pack"
author = "Vivian"
version = "1.1.16"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4629dfaf752858a1ebfa1b6adb0257d9d57d64e0a7254c56ca396ee094da077f"

[versions]
minecraft = "1.19.2"
quilt = "0.26.0"
