name = "Mods For The Pack"
author = "Vivian"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9f25ccc6e8d1d897e9973de551eca4f42838220e4180c6842560760f758a1ab7"

[versions]
minecraft = "1.19.2"
quilt = "0.26.0"
