name = "Mods For The Pack"
author = "Vivian"
version = "1.3.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4f1a11c24cae187764f42463d8ef6f37bcce7125c874fdffd87b4999865a7c82"

[versions]
minecraft = "1.19.2"
quilt = "0.26.0"
