name = "Mods For The Pack"
author = "Vivian"
version = "1.5.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b19cf72418a13c277e5dbcd278a0901374926fffa5fa6e3c2d19a6589c50dd09"

[versions]
minecraft = "1.19.2"
quilt = "0.26.0"
