name = "Mods For The Pack"
author = "Vivian"
version = "1.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cdf95f819fded38ff7d5e7b7eda07eae371f9350b4fc5a19ec3bada819a9c603"

[versions]
minecraft = "1.19.2"
quilt = "0.26.0"
