name = "Mods For The Pack"
author = "Vivian"
version = "1.2.12"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9333dfb955625d75a83350e5a37dc62e6d70c61780f74f09e1e80e9cae3e7f28"

[versions]
minecraft = "1.19.2"
quilt = "0.26.0"
