name = "Mods For The Pack"
author = "Vivian"
version = "1.1.30"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "49e1faccfa03cc58fb4a4c868f3dae1ef94816086a2be546289b17c9a8fc6dab"

[versions]
minecraft = "1.19.2"
quilt = "0.26.0"
