name = "Mods For The Pack"
author = "Vivian"
version = "1.1.19"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "644a7d26e705ff46f0c2647381a4c3ae4a3264afa6a9abdfe6e2b90d9974037e"

[versions]
minecraft = "1.19.2"
quilt = "0.26.0"
