name = "Mods For The Pack"
author = "Vivian"
version = "1.4.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "465ba4681b3c39419acbccaa4b37f4c14c8c517d76a13c28d6f775b35dbf15f4"

[versions]
minecraft = "1.19.2"
quilt = "0.26.0"
