name = "Mods For The Pack"
author = "Vivian"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "328492a6a2a96201f318057f845c424b2754556c7d78cdc9dfa0b9f53b2283c5"

[versions]
minecraft = "1.19.2"
quilt = "0.26.0"
