name = "Mods For The Pack"
author = "Vivian"
version = "1.4.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ff92a61cb4d637906ad5fa4f6db9793d54af2d15635b061501d2e635f49d3cef"

[versions]
minecraft = "1.19.2"
quilt = "0.26.0"
