name = "Mods For The Pack"
author = "Vivian"
version = "1.3.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ae32f6380eb42de4d6d6ca9fd9de15675be5f4f000801f7656de8dc43e0c52bd"

[versions]
minecraft = "1.19.2"
quilt = "0.26.0"
