name = "Mods For The Pack"
author = "Vivian"
version = "1.1.12"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7ad2562aa2b28dff1ecdc18aa19ad2e0d009bcfc011a9bce9813fa3a906dcb1b"

[versions]
minecraft = "1.19.2"
quilt = "0.26.0"
