name = "Mods For The Pack"
author = "Vivian"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "637cbd733d06c24ef22db5fda386acc82741b4b3eada563a23b65b715fceb4e6"

[versions]
minecraft = "1.19.2"
quilt = "0.26.0"
