name = "Mods For The Pack"
author = "Vivian"
version = "1.5.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "34398f9e53e8c54cf630c819ac1abc2797736a5f8ea6fcf3dffad792bdd643f8"

[versions]
minecraft = "1.19.2"
quilt = "0.26.0"
