name = "Mods For The Pack"
author = "Vivian"
version = "1.2.11"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c64a1912dd819314da37e4a69127f25f348cef7c47c75a6bdf46f519c2cd35aa"

[versions]
minecraft = "1.19.2"
quilt = "0.26.0"
